//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using System;
using System.Diagnostics;
using System.Drawing.Design;
using System.Windows.Forms;
using DslDiagrams = global::Microsoft.VisualStudio.Modeling.Diagrams;

namespace CE.DGH_DGC_SOM_IKP
{
	/// <summary>
	/// Helper class used to create and initialize toolbox items for this DSL.
	/// </summary>
	/// <remarks>
	/// Double-derived class to allow easier code customization.
	/// </remarks>
	public partial class DGH_DGC_SOM_IKPToolboxHelper : DGH_DGC_SOM_IKPToolboxHelperBase 
	{
		/// <summary>
		/// Constructs a new DGH_DGC_SOM_IKPToolboxHelper.
		/// </summary>
		public DGH_DGC_SOM_IKPToolboxHelper(global::System.IServiceProvider serviceProvider)
			: base(serviceProvider) { }
	}
	
	/// <summary>
	/// Helper class used to create and initialize toolbox items for this DSL.
	/// </summary>
	
	[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1001:TypesThatOwnDisposableFieldsShouldBeDisposable", Justification = "The store is disposed on domain shut down")]
	public abstract class DGH_DGC_SOM_IKPToolboxHelperBase
	{
		/// <summary>
		/// Toolbox item filter string used to identify DGH_DGC_SOM_IKP toolbox items.  
		/// </summary>
		/// <remarks>
		/// See the MSDN documentation for the ToolboxItemFilterAttribute class for more information on toolbox
		/// item filters.
		/// </remarks>
		public const string ToolboxFilterString = "DGH_DGC_SOM_IKP.1.0";
		/// <summary>
		/// Toolbox item filter string used to identify InicialTool connector tool.
		/// </summary>
		public const string InicialToolFilterString = "InicialTool.1.0";
		/// <summary>
		/// Toolbox item filter string used to identify FinalTool connector tool.
		/// </summary>
		public const string FinalToolFilterString = "FinalTool.1.0";
		/// <summary>
		/// Toolbox item filter string used to identify OrdenTool connector tool.
		/// </summary>
		public const string OrdenToolFilterString = "OrdenTool.1.0";
		/// <summary>
		/// Toolbox item filter string used to identify ProgramaImagenTool connector tool.
		/// </summary>
		public const string ProgramaImagenToolFilterString = "ProgramaImagenTool.1.0";
		/// <summary>
		/// Toolbox item filter string used to identify RepetirSubprogramaTool connector tool.
		/// </summary>
		public const string RepetirSubprogramaToolFilterString = "RepetirSubprogramaTool.1.0";

	
		private global::System.Collections.Generic.Dictionary<string, DslDesign::ModelingToolboxItem> toolboxItemCache = new global::System.Collections.Generic.Dictionary<string, DslDesign::ModelingToolboxItem>();
		private DslModeling::Store toolboxStore;
		
		private global::System.IServiceProvider sp;
		
		/// <summary>
		/// Constructs a new DGH_DGC_SOM_IKPToolboxHelperBase.
		/// </summary>
		protected DGH_DGC_SOM_IKPToolboxHelperBase(global::System.IServiceProvider serviceProvider)
		{
			if(serviceProvider == null) throw new global::System.ArgumentNullException("serviceProvider");
			
			this.sp = serviceProvider;
		}
		
		/// <summary>
		/// Serivce provider used to access services from the hosting environment.
		/// </summary>
		protected global::System.IServiceProvider ServiceProvider
		{
			get
			{
				return this.sp;
			}
		}

		/// <summary>
		/// Returns the display name of the tab that should be opened by default when the editor is opened.
		/// </summary>
		public static string DefaultToolboxTabName
		{
			get
			{
				return global::CE.DGH_DGC_SOM_IKP.DGH_DGC_SOM_IKPDomainModel.SingletonResourceManager.GetString("DGH_DGC_SOM_IKPToolboxTab", global::System.Globalization.CultureInfo.CurrentUICulture);
			}
		}
		
		
		/// <summary>
		/// Returns the toolbox items count in the default tool box tab.
		/// </summary>
		public static int DefaultToolboxTabToolboxItemsCount
		{
			get
			{
				return 13;
			}
		}
		

		/// <summary>
		/// Returns a list of custom toolbox items to be added dynamically
		/// </summary>
		public virtual global::System.Collections.Generic.IList<DslDesign::ModelingToolboxItem> CreateToolboxItems()
		{
			global::System.Collections.Generic.List<DslDesign::ModelingToolboxItem> toolboxItems = new global::System.Collections.Generic.List<DslDesign::ModelingToolboxItem>();
			return toolboxItems;
		}
		
		/// <summary>
		/// Creates an ElementGroupPrototype for the element tool corresponding to the given domain class id.
		/// Default behavior is to create a prototype containing an instance of the domain class.
		/// Derived classes may override this to add additional information to the prototype.
		/// </summary>
		protected virtual DslModeling::ElementGroupPrototype CreateElementToolPrototype(DslModeling::Store store, global::System.Guid domainClassId)
		{
			DslModeling::ModelElement element = store.ElementFactory.CreateElement(domainClassId);
			DslModeling::ElementGroup elementGroup = new DslModeling::ElementGroup(store.DefaultPartition);
			elementGroup.AddGraph(element, true);
			return elementGroup.CreatePrototype();
		}

		/// <summary>
		/// Returns instance of ModelingToolboxItem based on specified name.
		/// This method must be called from within a Transaction. Failure to do so will result in an exception
		/// </summary>
		/// <param name="itemId">unique name of desired ToolboxItem</param>
		/// <param name="store">Store to perform the operation against</param>
		/// <returns>An instance of ModelingToolboxItem if the itemId can be resolved, null otherwise</returns>
		public virtual DslDesign::ModelingToolboxItem GetToolboxItem(string itemId, DslModeling::Store store)
		{
			DslDesign::ModelingToolboxItem result = null;
			if (string.IsNullOrEmpty(itemId))
			{
				return null;
			}
			if (store == null)
			{
				return null;
			}
			global::System.Resources.ResourceManager resourceManager = global::CE.DGH_DGC_SOM_IKP.DGH_DGC_SOM_IKPDomainModel.SingletonResourceManager;
			global::System.Globalization.CultureInfo resourceCulture = global::System.Globalization.CultureInfo.CurrentUICulture;
			switch(itemId)
			{
				case "CE.DGH_DGC_SOM_IKP.ImagenToolToolboxItem":
					// Add ImagenTool shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"CE.DGH_DGC_SOM_IKP.ImagenToolToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						1, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("ImagenToolToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("ImagenToolToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"CE.DGH_DGC_SOM_IKP.DGH_DGC_SOM_IKPToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("DGH_DGC_SOM_IKPToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"ImagenTool", // F1 help keyword for the toolbox item.
						resourceManager.GetString("ImagenToolToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::CE.DGH_DGC_SOM_IKP.Imagen.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "CE.DGH_DGC_SOM_IKP.ProgramaToolToolboxItem":
					// Add ProgramaTool shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"CE.DGH_DGC_SOM_IKP.ProgramaToolToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						2, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("ProgramaToolToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("ProgramaToolToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"CE.DGH_DGC_SOM_IKP.DGH_DGC_SOM_IKPToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("DGH_DGC_SOM_IKPToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"ProgramaTool", // F1 help keyword for the toolbox item.
						resourceManager.GetString("ProgramaToolToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::CE.DGH_DGC_SOM_IKP.Programa.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "CE.DGH_DGC_SOM_IKP.ControlToolToolboxItem":
					// Add ControlTool shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"CE.DGH_DGC_SOM_IKP.ControlToolToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						3, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("ControlToolToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("ControlToolToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"CE.DGH_DGC_SOM_IKP.DGH_DGC_SOM_IKPToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("DGH_DGC_SOM_IKPToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"ControlTool", // F1 help keyword for the toolbox item.
						resourceManager.GetString("ControlToolToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::CE.DGH_DGC_SOM_IKP.InsRepetir.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "CE.DGH_DGC_SOM_IKP.ApuntarToolToolboxItem":
					// Add ApuntarTool shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"CE.DGH_DGC_SOM_IKP.ApuntarToolToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						4, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("ApuntarToolToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("ApuntarToolToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"CE.DGH_DGC_SOM_IKP.DGH_DGC_SOM_IKPToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("DGH_DGC_SOM_IKPToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"ApuntarTool", // F1 help keyword for the toolbox item.
						resourceManager.GetString("ApuntarToolToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::CE.DGH_DGC_SOM_IKP.InsApuntar.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "CE.DGH_DGC_SOM_IKP.FijarToolToolboxItem":
					// Add FijarTool shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"CE.DGH_DGC_SOM_IKP.FijarToolToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						5, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("FijarToolToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("FijarToolToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"CE.DGH_DGC_SOM_IKP.DGH_DGC_SOM_IKPToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("DGH_DGC_SOM_IKPToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"FijarTool", // F1 help keyword for the toolbox item.
						resourceManager.GetString("FijarToolToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::CE.DGH_DGC_SOM_IKP.InsFijar.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "CE.DGH_DGC_SOM_IKP.InicialToolToolboxItem":

					// Add InicialTool connector tool.
					result = new DslDesign::ModelingToolboxItem(
						"CE.DGH_DGC_SOM_IKP.InicialToolToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						6, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("InicialToolToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("InicialToolToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.				
						"CE.DGH_DGC_SOM_IKP.DGH_DGC_SOM_IKPToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("DGH_DGC_SOM_IKPToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"", // F1 help keyword for the toolbox item.
						resourceManager.GetString("InicialToolToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						null, // Connector toolbox items do not have an underlying data object.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require), 
							new global::System.ComponentModel.ToolboxItemFilterAttribute(InicialToolFilterString)
						});
					break;
				case "CE.DGH_DGC_SOM_IKP.FinalToolToolboxItem":

					// Add FinalTool connector tool.
					result = new DslDesign::ModelingToolboxItem(
						"CE.DGH_DGC_SOM_IKP.FinalToolToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						7, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("FinalToolToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("FinalToolToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.				
						"CE.DGH_DGC_SOM_IKP.DGH_DGC_SOM_IKPToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("DGH_DGC_SOM_IKPToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"FinalTool", // F1 help keyword for the toolbox item.
						resourceManager.GetString("FinalToolToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						null, // Connector toolbox items do not have an underlying data object.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require), 
							new global::System.ComponentModel.ToolboxItemFilterAttribute(FinalToolFilterString)
						});
					break;
				case "CE.DGH_DGC_SOM_IKP.OrdenToolToolboxItem":

					// Add OrdenTool connector tool.
					result = new DslDesign::ModelingToolboxItem(
						"CE.DGH_DGC_SOM_IKP.OrdenToolToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						8, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("OrdenToolToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("OrdenToolToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.				
						"CE.DGH_DGC_SOM_IKP.DGH_DGC_SOM_IKPToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("DGH_DGC_SOM_IKPToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"OrdenTool", // F1 help keyword for the toolbox item.
						resourceManager.GetString("OrdenToolToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						null, // Connector toolbox items do not have an underlying data object.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require), 
							new global::System.ComponentModel.ToolboxItemFilterAttribute(OrdenToolFilterString)
						});
					break;
				case "CE.DGH_DGC_SOM_IKP.PosicionToolToolboxItem":
					// Add PosicionTool shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"CE.DGH_DGC_SOM_IKP.PosicionToolToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						9, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("PosicionToolToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("PosicionToolToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"CE.DGH_DGC_SOM_IKP.DGH_DGC_SOM_IKPToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("DGH_DGC_SOM_IKPToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"PosicionTool", // F1 help keyword for the toolbox item.
						resourceManager.GetString("PosicionToolToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::CE.DGH_DGC_SOM_IKP.InsPosicion.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "CE.DGH_DGC_SOM_IKP.MoverToolToolboxItem":
					// Add MoverTool shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"CE.DGH_DGC_SOM_IKP.MoverToolToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						10, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("MoverToolToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("MoverToolToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"CE.DGH_DGC_SOM_IKP.DGH_DGC_SOM_IKPToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("DGH_DGC_SOM_IKPToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"MoverTool", // F1 help keyword for the toolbox item.
						resourceManager.GetString("MoverToolToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::CE.DGH_DGC_SOM_IKP.InsMover.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "CE.DGH_DGC_SOM_IKP.ProgramaImagenToolToolboxItem":

					// Add ProgramaImagenTool connector tool.
					result = new DslDesign::ModelingToolboxItem(
						"CE.DGH_DGC_SOM_IKP.ProgramaImagenToolToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						11, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("ProgramaImagenToolToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("ProgramaImagenToolToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.				
						"CE.DGH_DGC_SOM_IKP.DGH_DGC_SOM_IKPToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("DGH_DGC_SOM_IKPToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"ProgramaImagenTool", // F1 help keyword for the toolbox item.
						resourceManager.GetString("ProgramaImagenToolToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						null, // Connector toolbox items do not have an underlying data object.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require), 
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ProgramaImagenToolFilterString)
						});
					break;
				case "CE.DGH_DGC_SOM_IKP.RepetirSubprogramaToolToolboxItem":

					// Add RepetirSubprogramaTool connector tool.
					result = new DslDesign::ModelingToolboxItem(
						"CE.DGH_DGC_SOM_IKP.RepetirSubprogramaToolToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						12, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("RepetirSubprogramaToolToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("RepetirSubprogramaToolToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.				
						"CE.DGH_DGC_SOM_IKP.DGH_DGC_SOM_IKPToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("DGH_DGC_SOM_IKPToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"RepetirSubprogramaTool", // F1 help keyword for the toolbox item.
						resourceManager.GetString("RepetirSubprogramaToolToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						null, // Connector toolbox items do not have an underlying data object.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require), 
							new global::System.ComponentModel.ToolboxItemFilterAttribute(RepetirSubprogramaToolFilterString)
						});
					break;
				case "CE.DGH_DGC_SOM_IKP.SubprogramaToolToolboxItem":
					// Add SubprogramaTool shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"CE.DGH_DGC_SOM_IKP.SubprogramaToolToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						13, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("SubprogramaToolToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("SubprogramaToolToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"CE.DGH_DGC_SOM_IKP.DGH_DGC_SOM_IKPToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("DGH_DGC_SOM_IKPToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"SubprogramaTool", // F1 help keyword for the toolbox item.
						resourceManager.GetString("SubprogramaToolToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::CE.DGH_DGC_SOM_IKP.Subprograma.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				default:
					break;
			} // end switch
			
			return result;
		}
		

		/// <summary>
		/// The store toe be used for all the toolbox item creation
		/// </summary>
		protected DslModeling::Store ToolboxStore
		{
			get
			{ 
				if (toolboxStore==null)
				{
					toolboxStore = new DslModeling::Store(this.ServiceProvider);
					EventHandler StoreCleanUp = (o, e) =>
					{
						//Since Store implements IDisposable, we need to dispose it when we're finished
						if (this.toolboxStore != null)
						{
							this.toolboxStore.Dispose();
						}
						this.toolboxStore = null;
					};
					//There is no DomainUnload event for the default AppDomain, so we listen for both ProcessExit and DomainUnload
					AppDomain.CurrentDomain.ProcessExit += new EventHandler(StoreCleanUp);
					AppDomain.CurrentDomain.DomainUnload += new EventHandler(StoreCleanUp);
					
					//load the domain model
					toolboxStore.LoadDomainModels(typeof(global::CE.DGH_DGC_SOM_IKP.DGH_DGC_SOM_IKPDomainModel));
					
				}
				return toolboxStore;
			}
		}
		
		/// <summary>
		/// Given a toolbox item "unique ID" returns the the toolbox item using cached dictionary
		/// </summary>
		/// <param name="itemId">The unique ToolboxItem to retrieve</param>
		private DslDesign::ModelingToolboxItem GetToolboxItem(string itemId)
		{
			DslDesign::ModelingToolboxItem item = null;

			if (!this.toolboxItemCache.TryGetValue(itemId, out item))
			{
				DslModeling::Store store = this.ToolboxStore;
				
				// Open transaction so we can create model elements corresponding to toolbox items.
				using (DslModeling::Transaction t = store.TransactionManager.BeginTransaction("CreateToolboxItems"))
				{
					// Retrieve the specified ToolboxItem from the DSL
					this.toolboxItemCache[itemId] = item = this.GetToolboxItem(itemId, store);
				}
			}

			return item;
		}
		
		/// <summary>
		/// Given a toolbox item "unique ID" and a data format identifier, returns the content of
		/// the data format. 
		/// </summary>
		/// <param name="itemId">The unique ToolboxItem to retrieve data for</param>
		/// <param name="format">The desired format of the resulting data</param>
		public virtual object GetToolboxItemData(string itemId, DataFormats.Format format)
		{
			DslDesign::ModelingToolboxItem item = null;

			global::System.Resources.ResourceManager resourceManager = global::CE.DGH_DGC_SOM_IKP.DGH_DGC_SOM_IKPDomainModel.SingletonResourceManager;
			global::System.Globalization.CultureInfo resourceCulture = global::System.Globalization.CultureInfo.CurrentUICulture;

			System.Windows.Forms.IDataObject tbxDataObj;

			//get the toolbox item
			item = GetToolboxItem(itemId);

			if (item != null)
			{
				ToolboxItemContainer container = new ToolboxItemContainer(item);
				tbxDataObj = container.ToolboxData;

				if (tbxDataObj.GetDataPresent(format.Name))
				{
					return tbxDataObj.GetData(format.Name);
				}
				else 
				{
					string invalidFormatString = resourceManager.GetString("UnsupportedToolboxFormat", resourceCulture);
					throw new InvalidOperationException(string.Format(resourceCulture, invalidFormatString, format.Name));
				}
			}

			string errorFormatString = resourceManager.GetString("UnresolvedToolboxItem", resourceCulture);
			throw new InvalidOperationException(string.Format(resourceCulture, errorFormatString, itemId));
		}		
	}
}
