//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CE.DGH_DGC_SOM_IKP
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "DGH_DGC_SOM_IKP";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"DGH_DGC_SOM_IKP";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"CE";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID DGH_DGC_SOM_IKPDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(DGH_DGC_SOM_IKPCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID DGH_DGC_SOM_IKPExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(DGH_DGC_SOM_IKPCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewDGH_DGC_SOM_IKPExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(DGH_DGC_SOM_IKPCommandSetId), 0x0001);
	
		// Package identifier
		public const string DGH_DGC_SOM_IKPPackageId = "b6eee23c-71e3-44f4-9fbe-921f798446cf";
		
		// Editor factory identifier
		public const string DGH_DGC_SOM_IKPEditorFactoryId = "59f7e28b-c170-456b-a62b-58b835bd889f";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string DGH_DGC_SOM_IKPModelExplorerToolWindowId = "85a37985-8134-4416-ac60-a3fac65719a5";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace CE.DGH_DGC_SOM_IKP
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string DGH_DGC_SOM_IKPCommandSetId = "2942f35b-70c4-41a4-ac21-432018234b20";
	}
}