//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using VSShellInterop = global::Microsoft.VisualStudio.Shell.Interop;
using VSShell = global::Microsoft.VisualStudio.Shell;
using DslShell = global::Microsoft.VisualStudio.Modeling.Shell;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslModeling = global::Microsoft.VisualStudio.Modeling;
using VSTextTemplatingHost = global::Microsoft.VisualStudio.TextTemplating.VSHost;
using System;
using System.Diagnostics;
using System.Drawing.Design;
using System.Linq;
using System.Windows.Forms;
	
namespace CE.DGH_DGC_SOM_IKP
{
	/// <summary>
	/// This class implements the VS package that integrates this DSL into Visual Studio.
	/// </summary>
	[VSShell::DefaultRegistryRoot("Software\\Microsoft\\VisualStudio\\10.0")]
	[VSShell::PackageRegistration(RegisterUsing = VSShell::RegistrationMethod.Assembly, UseManagedResourcesOnly = true)]
	[VSShell::ProvideToolWindow(typeof(DGH_DGC_SOM_IKPExplorerToolWindow), MultiInstances = false, Style = VSShell::VsDockStyle.Tabbed, Orientation = VSShell::ToolWindowOrientation.Right, Window = "{3AE79031-E1BC-11D0-8F78-00A0C9110057}")]
	[VSShell::ProvideToolWindowVisibility(typeof(DGH_DGC_SOM_IKPExplorerToolWindow), Constants.DGH_DGC_SOM_IKPEditorFactoryId)]
	[VSShell::ProvideStaticToolboxGroup("@DGH_DGC_SOM_IKPToolboxTab;CE.DGH_DGC_SOM_IKP.Dsl.dll", "CE.DGH_DGC_SOM_IKP.DGH_DGC_SOM_IKPToolboxTab")]
	[VSShell::ProvideStaticToolboxItem("CE.DGH_DGC_SOM_IKP.DGH_DGC_SOM_IKPToolboxTab",
					"@ImagenToolToolboxItem;CE.DGH_DGC_SOM_IKP.Dsl.dll", 
					"CE.DGH_DGC_SOM_IKP.ImagenToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"ImagenTool", 
					"@ImagenToolToolboxBitmap;CE.DGH_DGC_SOM_IKP.Dsl.dll", 
					0xff00ff)]
	[VSShell::ProvideStaticToolboxItem("CE.DGH_DGC_SOM_IKP.DGH_DGC_SOM_IKPToolboxTab",
					"@ProgramaToolToolboxItem;CE.DGH_DGC_SOM_IKP.Dsl.dll", 
					"CE.DGH_DGC_SOM_IKP.ProgramaToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"ProgramaTool", 
					"@ProgramaToolToolboxBitmap;CE.DGH_DGC_SOM_IKP.Dsl.dll", 
					0xff00ff)]
	[VSShell::ProvideStaticToolboxItem("CE.DGH_DGC_SOM_IKP.DGH_DGC_SOM_IKPToolboxTab",
					"@ControlToolToolboxItem;CE.DGH_DGC_SOM_IKP.Dsl.dll", 
					"CE.DGH_DGC_SOM_IKP.ControlToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"ControlTool", 
					"@ControlToolToolboxBitmap;CE.DGH_DGC_SOM_IKP.Dsl.dll", 
					0xff00ff)]
	[VSShell::ProvideStaticToolboxItem("CE.DGH_DGC_SOM_IKP.DGH_DGC_SOM_IKPToolboxTab",
					"@ApuntarToolToolboxItem;CE.DGH_DGC_SOM_IKP.Dsl.dll", 
					"CE.DGH_DGC_SOM_IKP.ApuntarToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"ApuntarTool", 
					"@ApuntarToolToolboxBitmap;CE.DGH_DGC_SOM_IKP.Dsl.dll", 
					0xff00ff)]
	[VSShell::ProvideStaticToolboxItem("CE.DGH_DGC_SOM_IKP.DGH_DGC_SOM_IKPToolboxTab",
					"@FijarToolToolboxItem;CE.DGH_DGC_SOM_IKP.Dsl.dll", 
					"CE.DGH_DGC_SOM_IKP.FijarToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"FijarTool", 
					"@FijarToolToolboxBitmap;CE.DGH_DGC_SOM_IKP.Dsl.dll", 
					0xff00ff)]
	[VSShell::ProvideStaticToolboxItem("CE.DGH_DGC_SOM_IKP.DGH_DGC_SOM_IKPToolboxTab",
					"@InicialToolToolboxItem;CE.DGH_DGC_SOM_IKP.Dsl.dll", 
					"CE.DGH_DGC_SOM_IKP.InicialToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"", 
					"@InicialToolToolboxBitmap;CE.DGH_DGC_SOM_IKP.Dsl.dll", 
					0xff00ff)]
	[VSShell::ProvideStaticToolboxItem("CE.DGH_DGC_SOM_IKP.DGH_DGC_SOM_IKPToolboxTab",
					"@FinalToolToolboxItem;CE.DGH_DGC_SOM_IKP.Dsl.dll", 
					"CE.DGH_DGC_SOM_IKP.FinalToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"FinalTool", 
					"@FinalToolToolboxBitmap;CE.DGH_DGC_SOM_IKP.Dsl.dll", 
					0xff00ff)]
	[VSShell::ProvideStaticToolboxItem("CE.DGH_DGC_SOM_IKP.DGH_DGC_SOM_IKPToolboxTab",
					"@OrdenToolToolboxItem;CE.DGH_DGC_SOM_IKP.Dsl.dll", 
					"CE.DGH_DGC_SOM_IKP.OrdenToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"OrdenTool", 
					"@OrdenToolToolboxBitmap;CE.DGH_DGC_SOM_IKP.Dsl.dll", 
					0xff00ff)]
	[VSShell::ProvideStaticToolboxItem("CE.DGH_DGC_SOM_IKP.DGH_DGC_SOM_IKPToolboxTab",
					"@PosicionToolToolboxItem;CE.DGH_DGC_SOM_IKP.Dsl.dll", 
					"CE.DGH_DGC_SOM_IKP.PosicionToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"PosicionTool", 
					"@PosicionToolToolboxBitmap;CE.DGH_DGC_SOM_IKP.Dsl.dll", 
					0xff00ff)]
	[VSShell::ProvideStaticToolboxItem("CE.DGH_DGC_SOM_IKP.DGH_DGC_SOM_IKPToolboxTab",
					"@MoverToolToolboxItem;CE.DGH_DGC_SOM_IKP.Dsl.dll", 
					"CE.DGH_DGC_SOM_IKP.MoverToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"MoverTool", 
					"@MoverToolToolboxBitmap;CE.DGH_DGC_SOM_IKP.Dsl.dll", 
					0xff00ff)]
	[VSShell::ProvideStaticToolboxItem("CE.DGH_DGC_SOM_IKP.DGH_DGC_SOM_IKPToolboxTab",
					"@ProgramaImagenToolToolboxItem;CE.DGH_DGC_SOM_IKP.Dsl.dll", 
					"CE.DGH_DGC_SOM_IKP.ProgramaImagenToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"ProgramaImagenTool", 
					"@ProgramaImagenToolToolboxBitmap;CE.DGH_DGC_SOM_IKP.Dsl.dll", 
					0xff00ff)]
	[VSShell::ProvideStaticToolboxItem("CE.DGH_DGC_SOM_IKP.DGH_DGC_SOM_IKPToolboxTab",
					"@RepetirSubprogramaToolToolboxItem;CE.DGH_DGC_SOM_IKP.Dsl.dll", 
					"CE.DGH_DGC_SOM_IKP.RepetirSubprogramaToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"RepetirSubprogramaTool", 
					"@RepetirSubprogramaToolToolboxBitmap;CE.DGH_DGC_SOM_IKP.Dsl.dll", 
					0xff00ff)]
	[VSShell::ProvideStaticToolboxItem("CE.DGH_DGC_SOM_IKP.DGH_DGC_SOM_IKPToolboxTab",
					"@SubprogramaToolToolboxItem;CE.DGH_DGC_SOM_IKP.Dsl.dll", 
					"CE.DGH_DGC_SOM_IKP.SubprogramaToolToolboxItem", 
					"CF_TOOLBOXITEMCONTAINER,CF_TOOLBOXITEMCONTAINER_HASH,CF_TOOLBOXITEMCONTAINER_CONTENTS", 
					"SubprogramaTool", 
					"@SubprogramaToolToolboxBitmap;CE.DGH_DGC_SOM_IKP.Dsl.dll", 
					0xff00ff)]
	[VSShell::ProvideEditorFactory(typeof(DGH_DGC_SOM_IKPEditorFactory), 103, TrustLevel = VSShellInterop::__VSEDITORTRUSTLEVEL.ETL_AlwaysTrusted)]
	[VSShell::ProvideEditorExtension(typeof(DGH_DGC_SOM_IKPEditorFactory), "." + Constants.DesignerFileExtension, 50)]
	[DslShell::ProvideRelatedFile("." + Constants.DesignerFileExtension, Constants.DefaultDiagramExtension,
		ProjectSystem = DslShell::ProvideRelatedFileAttribute.CSharpProjectGuid,
		FileOptions = DslShell::RelatedFileType.FileName)]
	[DslShell::ProvideRelatedFile("." + Constants.DesignerFileExtension, Constants.DefaultDiagramExtension,
		ProjectSystem = DslShell::ProvideRelatedFileAttribute.VisualBasicProjectGuid,
		FileOptions = DslShell::RelatedFileType.FileName)]
	[DslShell::RegisterAsDslToolsEditor]
	[global::System.Runtime.InteropServices.ComVisible(true)]
	[DslShell::ProvideBindingPath]
	[DslShell::ProvideXmlEditorChooserBlockSxSWithXmlEditor(@"DGH_DGC_SOM_IKP", typeof(DGH_DGC_SOM_IKPEditorFactory))]
	internal abstract partial class DGH_DGC_SOM_IKPPackageBase : DslShell::ModelingPackage
	{
		protected global::CE.DGH_DGC_SOM_IKP.DGH_DGC_SOM_IKPToolboxHelper toolboxHelper;	
		
		/// <summary>
		/// Initialization method called by the package base class when this package is loaded.
		/// </summary>
		protected override void Initialize()
		{
			base.Initialize();

			// Register the editor factory used to create the DSL editor.
			this.RegisterEditorFactory(new DGH_DGC_SOM_IKPEditorFactory(this));
			
			// Initialize the toolbox helper
			toolboxHelper = new global::CE.DGH_DGC_SOM_IKP.DGH_DGC_SOM_IKPToolboxHelper(this);

			// Create the command set that handles menu commands provided by this package.
			DGH_DGC_SOM_IKPCommandSet commandSet = new DGH_DGC_SOM_IKPCommandSet(this);
			commandSet.Initialize();
			
			// Create the command set that handles cut/copy/paste commands provided by this package.
			DGH_DGC_SOM_IKPClipboardCommandSet clipboardCommandSet = new DGH_DGC_SOM_IKPClipboardCommandSet(this);
			clipboardCommandSet.Initialize();
			
			// Register the model explorer tool window for this DSL.
			this.AddToolWindow(typeof(DGH_DGC_SOM_IKPExplorerToolWindow));

			// Initialize Extension Registars
			// this is a partial method call
			this.InitializeExtensions();

			// Add dynamic toolbox items
			this.SetupDynamicToolbox();
		}

		/// <summary>
		/// Partial method to initialize ExtensionRegistrars (if any) in the DslPackage
		/// </summary>
		partial void InitializeExtensions();
		
		/// <summary>
		/// Returns any dynamic tool items for the designer
		/// </summary>
		/// <remarks>The default implementation is to return the list of items from the generated toolbox helper.</remarks>
		protected override global::System.Collections.Generic.IList<DslDesign::ModelingToolboxItem> CreateToolboxItems()
		{
			try
			{
				Debug.Assert(toolboxHelper != null, "Toolbox helper is not initialized");
				return toolboxHelper.CreateToolboxItems();
			}
			catch(global::System.Exception e)
			{
				global::System.Diagnostics.Debug.Fail("Exception thrown during toolbox item creation.  This may result in Package Load Failure:\r\n\r\n" + e);
				throw;
			}
		}
		
		
		/// <summary>
		/// Given a toolbox item "unique ID" and a data format identifier, returns the content of
		/// the data format. 
		/// </summary>
		/// <param name="itemId">The unique ToolboxItem to retrieve data for</param>
		/// <param name="format">The desired format of the resulting data</param>
		protected override object GetToolboxItemData(string itemId, DataFormats.Format format)
		{
			Debug.Assert(toolboxHelper != null, "Toolbox helper is not initialized");
		
			// Retrieve the specified ToolboxItem from the DSL
			return toolboxHelper.GetToolboxItemData(itemId, format);
		}
	}

}

//
// Package attributes which may need to change are placed on the partial class below, rather than in the main include file.
//
namespace CE.DGH_DGC_SOM_IKP
{
	/// <summary>
	/// Double-derived class to allow easier code customization.
	/// </summary>
	[VSShell::ProvideMenuResource("1000.ctmenu", 1)]
	[VSShell::ProvideToolboxItems(1)]
	[VSTextTemplatingHost::ProvideDirectiveProcessor(typeof(global::CE.DGH_DGC_SOM_IKP.DGH_DGC_SOM_IKPDirectiveProcessor), global::CE.DGH_DGC_SOM_IKP.DGH_DGC_SOM_IKPDirectiveProcessor.DGH_DGC_SOM_IKPDirectiveProcessorName, "A directive processor that provides access to DGH_DGC_SOM_IKP files")]
	[global::System.Runtime.InteropServices.Guid(Constants.DGH_DGC_SOM_IKPPackageId)]
	internal sealed partial class DGH_DGC_SOM_IKPPackage : DGH_DGC_SOM_IKPPackageBase
	{
	}
}